function micfr = load_microphone_fr(filename)
% micfr = load_microphone_fr(filename)
%
%	Function to read in microphone calibration data (*_fr.mat)
%	generated by the CalirateHeadphoneMic program.
%
%	Input Arguments:
%		filename		= 	name of cal file (usually *_fr.cal)
%		
%	Output Arguments:
%		micfr			= 	Matlab structure containing cal data
%
%	See also: CalibrateHeadphoneMic;


% Sharad J. Shanbhag
% sshanbha@aecom.yu.edu
% Version 1.00

if ~exist(filename)
	error(['Frequency response file ' filename ' not found']);
end

load(filename);

micfr = caldata;
